"""empty message

Revision ID: 0463818862cd
Revises: 
Create Date: 2024-09-30 07:09:31.393317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0463818862cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometria', schema=None) as batch_op:
        batch_op.drop_column('natalidad')
        batch_op.drop_column('mortalidad')

    with op.batch_alter_table('estanque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('natalidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mortalidad', sa.Integer(), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=mysql.ENUM('Admin', 'Aprendiz', 'Instructor'),
               type_=sa.Enum('Admin', 'Instructor', 'Aprendiz'),
               existing_nullable=True)
        batch_op.alter_column('contrasena',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['nuip'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('contrasena',
               existing_type=sa.VARCHAR(length=300),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('rol',
               existing_type=sa.Enum('Admin', 'Instructor', 'Aprendiz'),
               type_=mysql.ENUM('Admin', 'Aprendiz', 'Instructor'),
               existing_nullable=True)

    with op.batch_alter_table('estanque', schema=None) as batch_op:
        batch_op.drop_column('mortalidad')
        batch_op.drop_column('natalidad')

    with op.batch_alter_table('biometria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mortalidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('natalidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
