"""empty message

Revision ID: 3b4d45b1654c
Revises: c5d052fab0f5
Create Date: 2024-08-21 10:11:35.916409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4d45b1654c'
down_revision = 'c5d052fab0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('iduser', sa.INTEGER(), nullable=False),
    sa.Column('nombres', sa.String(length=200), nullable=True),
    sa.Column('apellidos', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nuip', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('iduser')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
