"""empty message

Revision ID: 455cd912ad35
Revises: 
Create Date: 2024-10-25 21:47:32.675005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '455cd912ad35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad', sa.String(length=10), nullable=True))
        batch_op.alter_column('cantidadSemilla',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peces', schema=None) as batch_op:
        batch_op.alter_column('cantidadSemilla',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('unidad')

    # ### end Alembic commands ###
