"""empty message

Revision ID: 4a919a15135a
Revises: 
Create Date: 2024-09-23 14:51:46.430332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a919a15135a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometria', schema=None) as batch_op:
        batch_op.drop_column('natalidad')
        batch_op.drop_column('mortalidad')

    with op.batch_alter_table('estanque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('natalidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mortalidad', sa.Integer(), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('Admin', 'Instructor', 'Aprendiz'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.Enum('Admin', 'Instructor', 'Aprendiz'),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    with op.batch_alter_table('estanque', schema=None) as batch_op:
        batch_op.drop_column('mortalidad')
        batch_op.drop_column('natalidad')

    with op.batch_alter_table('biometria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mortalidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('natalidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
