"""empty message

Revision ID: 52110b82b4bf
Revises: 745766365fc9
Create Date: 2024-10-18 01:37:45.957059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52110b82b4bf'
down_revision = '745766365fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora', sa.Time(), nullable=True))
        batch_op.alter_column('fecha',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometria', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('hora')

    # ### end Alembic commands ###
