"""empty message

Revision ID: 745766365fc9
Revises: b1e18683e0c6
Create Date: 2024-10-17 21:25:22.351129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '745766365fc9'
down_revision = 'b1e18683e0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estanque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tamanoEstanque', sa.Integer(), nullable=True))
        batch_op.drop_column('tamañoEstanque')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estanque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tamañoEstanque', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('tamanoEstanque')

    # ### end Alembic commands ###
