"""empty message

Revision ID: c2d37393f4f2
Revises: 
Create Date: 2024-11-16 07:57:46.680966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d37393f4f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alimento',
    sa.Column('idAlimento', sa.Integer(), nullable=False),
    sa.Column('NombreAlimento', sa.String(length=1000), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('idAlimento')
    )
    op.create_table('peces',
    sa.Column('id_pez', sa.Integer(), nullable=False),
    sa.Column('nombre_cientifico', sa.String(length=1000), nullable=True),
    sa.Column('cantidadSemilla', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_pez')
    )
    op.create_table('usuario',
    sa.Column('iduser', sa.INTEGER(), nullable=False),
    sa.Column('nombres', sa.String(length=200), nullable=True),
    sa.Column('apellidos', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nuip', sa.INTEGER(), nullable=True),
    sa.Column('rol', sa.Enum('Admin', 'Instructor', 'Aprendiz'), nullable=True),
    sa.Column('contrasena', sa.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('iduser'),
    sa.UniqueConstraint('nuip')
    )
    op.create_table('estanque',
    sa.Column('id_estanque', sa.Integer(), nullable=False),
    sa.Column('id_pez', sa.Integer(), nullable=True),
    sa.Column('tamanoEstanque', sa.Integer(), nullable=True),
    sa.Column('numeropeces', sa.Integer(), nullable=True),
    sa.Column('nombreEstanque', sa.String(length=500), nullable=True),
    sa.Column('natalidad', sa.Integer(), nullable=True),
    sa.Column('mortalidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pez'], ['peces.id_pez'], ),
    sa.PrimaryKeyConstraint('id_estanque')
    )
    op.create_table('alimentacion',
    sa.Column('idalimentacion', sa.Integer(), nullable=False),
    sa.Column('idAlimento', sa.Integer(), nullable=True),
    sa.Column('id_estanque', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('observaciones', sa.String(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['idAlimento'], ['alimento.idAlimento'], ),
    sa.ForeignKeyConstraint(['id_estanque'], ['estanque.id_estanque'], ),
    sa.PrimaryKeyConstraint('idalimentacion')
    )
    op.create_table('biometria',
    sa.Column('id_biometria', sa.Integer(), nullable=False),
    sa.Column('id_estanque', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('tamano_muestra', sa.Integer(), nullable=True),
    sa.Column('cantidad_biomasa', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_estanque'], ['estanque.id_estanque'], ),
    sa.PrimaryKeyConstraint('id_biometria')
    )
    op.create_table('wq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_estanque', sa.Integer(), nullable=True),
    sa.Column('nitrogeno', sa.Float(), nullable=True),
    sa.Column('oxigeno', sa.Float(), nullable=True),
    sa.Column('sulfuro', sa.Float(), nullable=True),
    sa.Column('nitratos', sa.Float(), nullable=True),
    sa.Column('informacion', sa.String(length=1000), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['id_estanque'], ['estanque.id_estanque'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wq')
    op.drop_table('biometria')
    op.drop_table('alimentacion')
    op.drop_table('estanque')
    op.drop_table('usuario')
    op.drop_table('peces')
    op.drop_table('alimento')
    # ### end Alembic commands ###
