"""empty message

Revision ID: c3154bf868a0
Revises: e94595285b86
Create Date: 2024-10-23 16:05:33.547653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3154bf868a0'
down_revision = 'e94595285b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wq', schema=None) as batch_op:
        batch_op.alter_column('informacion',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wq', schema=None) as batch_op:
        batch_op.alter_column('informacion',
               existing_type=sa.String(length=1000),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
