"""empty message

Revision ID: c5d052fab0f5
Revises: 
Create Date: 2024-08-21 08:46:29.743251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5d052fab0f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('pid', mysql.DOUBLE(asdecimal=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=False),
    sa.Column('age', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.PrimaryKeyConstraint('pid'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
