"""empty message

Revision ID: cb253f3f661b
Revises: 52110b82b4bf
Create Date: 2024-10-18 01:43:07.863202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb253f3f661b'
down_revision = '52110b82b4bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometria', schema=None) as batch_op:
        batch_op.drop_constraint('biometria_ibfk_1', type_='foreignkey')
        batch_op.drop_column('id_pez')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pez', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('biometria_ibfk_1', 'peces', ['id_pez'], ['id_pez'])

    # ### end Alembic commands ###
