"""empty message

Revision ID: e3c8c5a78daf
Revises: 
Create Date: 2024-11-21 21:25:20.521705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3c8c5a78daf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ozono', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('temperatura', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('PH', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('Dureza', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('magnesio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('manganezo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calcio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('CO2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('amoniototal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('amonionioNH3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cloro', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('HCN', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('GasMetano', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cadmio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cromo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cobre', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hierro', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mercurio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('niquel', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('plomo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('turbidez', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('solidosdisueltos', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sulfatos', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('zinc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fosfatos', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fosforosoluble', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sulfurodehidrogeno', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fosforototal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nitritos', sa.Float(), nullable=True))
        batch_op.drop_column('nitratos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nitratos', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('nitritos')
        batch_op.drop_column('fosforototal')
        batch_op.drop_column('sulfurodehidrogeno')
        batch_op.drop_column('fosforosoluble')
        batch_op.drop_column('fosfatos')
        batch_op.drop_column('zinc')
        batch_op.drop_column('sulfatos')
        batch_op.drop_column('solidosdisueltos')
        batch_op.drop_column('turbidez')
        batch_op.drop_column('plomo')
        batch_op.drop_column('niquel')
        batch_op.drop_column('mercurio')
        batch_op.drop_column('hierro')
        batch_op.drop_column('cobre')
        batch_op.drop_column('cromo')
        batch_op.drop_column('cadmio')
        batch_op.drop_column('GasMetano')
        batch_op.drop_column('HCN')
        batch_op.drop_column('cloro')
        batch_op.drop_column('amonionioNH3')
        batch_op.drop_column('amoniototal')
        batch_op.drop_column('CO2')
        batch_op.drop_column('calcio')
        batch_op.drop_column('manganezo')
        batch_op.drop_column('magnesio')
        batch_op.drop_column('Dureza')
        batch_op.drop_column('PH')
        batch_op.drop_column('temperatura')
        batch_op.drop_column('ozono')

    # ### end Alembic commands ###
