"""empty message

Revision ID: e94595285b86
Revises: cb253f3f661b
Create Date: 2024-10-19 08:46:51.758376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94595285b86'
down_revision = 'cb253f3f661b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estanque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numeropeces', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estanque', schema=None) as batch_op:
        batch_op.drop_column('numeropeces')

    # ### end Alembic commands ###
