
from sqlalchemy import Integer, ForeignKey,Date,  Date, Time
from sqlalchemy.orm import relationship
from extensions import db

class wq(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    id_estanque = db.Column(Integer, ForeignKey('estanque.id_estanque'))
    nitrogeno = db.Column(db.Float)
    ozono = db.Column(db.Float)
    temperatura = db.Column(db.Float)
    PH = db.Column(db.Float)
    Dureza = db.Column(db.Float)
    magnesio = db.Column(db.Float)
    manganezo = db.Column(db.Float)
    calcio = db.Column(db.Float)
    CO2 = db.Column(db.Float)
    amoniototal = db.Column(db.Float)
    amonionioNH3 = db.Column(db.Float)
    oxigeno = db.Column(db.Float)
    sulfuro = db.Column(db.Float)
    cloro = db.Column(db.Float)
    HCN = db.Column(db.Float)
    GasMetano = db.Column(db.Float)
    cadmio = db.Column(db.Float)
    cromo = db.Column(db.Float)
    cobre   = db.Column(db.Float)
    hierro = db.Column(db.Float)
    mercurio = db.Column(db.Float)
    niquel = db.Column(db.Float)
    plomo = db.Column(db.Float)
    turbidez = db.Column(db.Float)
    solidosdisueltos = db.Column(db.Float)
    sulfatos = db.Column(db.Float)
    zinc = db.Column(db.Float)
    fosfatos = db.Column(db.Float)
    fosforosoluble = db.Column(db.Float)
    sulfurodehidrogeno = db.Column(db.Float)
    fosforototal = db.Column(db.Float)
    nitritos = db.Column(db.Float)
    informacion = db.Column(db.String(1000))
    fecha = db.Column(Date) 
    hora = db.Column(Time)